import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "GoodPlates - React",
	description: "Generated by my fingers on a keyboard",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
