import type { Metadata } from "next";
import HeaderGP from "./components/HeaderGP/headerGP";
import "./globals.scss";

export const metadata: Metadata = {
	title: "GoodPlates - React",
	description: "Generated by my fingers on a keyboard",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<HeaderGP />
				{children}
			</body>
		</html>
	);
}
